var nodes= [{"name":"Al Bagno di Nerone"},
{"name":"Ristoro Re di Puglia"},
{"name":"La Mescita"},
{"name":"L\'Artilafo"},
{"name":"Sottobosco Libri&Cafe"},
{"name":"Ristorante Il Granaio"},
{"name":"Zen"},
{"name":"Skip!"},
{"name":"Gelateria Tuffo 13"},
{"name":"L\'Ostellino"},
{"name":"Ristorante Greco Itaca"},
{"name":"Subway"},
{"name":"Wok World"},
{"name":"Pizzeria da Mois"},
{"name":"Bollicine Cafe\'"},
{"name":"Hostaria Le Repubbliche Marinare"},
{"name":"Ristoro Pecorino"},
{"name":"pizzeria da pancino"},
{"name":"Kobe sushi restaurant"},
{"name":"Osteria San Paolo"},
{"name":"La Grotta"},
{"name":"Ristorane Pizzeria La Cereria"},
{"name":"La Regginella"},
{"name":"Pizzamania"},
{"name":"Pizzeria da Jo\'"},
{"name":"Ristoro Amaltea"},
{"name":"Mondo Doner Kebab"},
{"name":"Ristorante\/pizzeria L\'Arciere"},
{"name":"La Taverna di Pulcinella"},
{"name":"Cereria alle porte"},
{"name":"Pizzeria Da Filippo"},
{"name":"La Carta Gialla di G.Leonardi & C. SAS"},
{"name":"Antica Trattoria Da Bruno"},
{"name":"Ristorante  Asuka"},
{"name":"Numeroundici"},
{"name":"Antica Bottega di Pisa"},
{"name":"Sunset Cafe"},
{"name":"Hosteria da Fermento"},
{"name":"India Ristorante"},
{"name":"Pizzeria Da Nando"},
{"name":"Il fornaccio"},
{"name":"Pizzeria L\'Acquolina"},
{"name":"Lo Sfizio"},
{"name":"Bazeel"},
{"name":"Il Crudo"},
{"name":"Osteria dei Cavalieri"},
{"name":"Gusto al 129"},
{"name":"Le Scuderie"},
{"name":"Caino Caff Contemporaneo"},
{"name":"Ristorante Shanghai"},
{"name":"Caffe Letterario Volta Pagina"},
{"name":"COL4_1"},
{"name":"Pizzeria La Tombola"},
{"name":"COL4_2"},
{"name":"Show Club Restaurant"},
{"name":"COL4_4"},
{"name":"La Piccola Capri"},
{"name":"ControKebab"},
{"name":"Osteria la Toscana"},
{"name":"Paninoteca Mediceo"},
{"name":"Edo Sushi House"},
{"name":"Pizzeria Nika"},
{"name":"Caffe Gambrinus"},
{"name":"I Porci Comodi"},
{"name":"Pizzeria Funiculi"},
{"name":"Sciue Sciue"},
{"name":"Paninoteca Il Canguro"},
{"name":"Mani\'omio"},
{"name":"Tanduri Ristorante Indiano"},
{"name":"Pizzeria Funiculi-Funicula"},
{"name":"Happy Pizza"},
{"name":"Ristorante Pechino"},
{"name":"Anni\'80-Ristorante Cinese"},
{"name":"Namaste India Ristorante"},
{"name":"Al Madina"},
{"name":"Pizzeria La Paradisea"},
{"name":"Gelateria Ghibli 2"},
{"name":"Nice Wok"},
{"name":"COL4_5"},
{"name":"Circolo Culturale Greco Makedonia"},
{"name":"Bella Napoli - Pizzeria"},
{"name":"Osteria  Del Tinti"},
{"name":"Pia Para Ti"},
{"name":"Osteria in domo"},
{"name":"Pizzeria Martino"},
{"name":"Euro Kebab"},
{"name":"Mim Caf"},
{"name":"Agriturismo Tenuta Il Pino"},
{"name":"Osteria Bernardo"},
{"name":"Pizzeria Il Montino"},
]
var links = [{ source: nodes[0], target: nodes[89]},
{ source: nodes[0], target: nodes[39]},
{ source: nodes[0], target: nodes[30]},
{ source: nodes[0], target: nodes[17]},
{ source: nodes[0], target: nodes[13]},
{ source: nodes[0], target: nodes[61]},
{ source: nodes[0], target: nodes[70]},
{ source: nodes[1], target: nodes[5]},
{ source: nodes[2], target: nodes[20]},
{ source: nodes[2], target: nodes[45]},
{ source: nodes[2], target: nodes[81]},
{ source: nodes[3], target: nodes[88]},
{ source: nodes[4], target: nodes[50]},
{ source: nodes[5], target: nodes[1]},
{ source: nodes[6], target: nodes[18]},
{ source: nodes[6], target: nodes[33]},
{ source: nodes[6], target: nodes[77]},
{ source: nodes[6], target: nodes[12]},
{ source: nodes[6], target: nodes[60]},
{ source: nodes[7], target: nodes[59]},
{ source: nodes[7], target: nodes[44]},
{ source: nodes[8], target: nodes[76]},
{ source: nodes[9], target: nodes[63]},
{ source: nodes[9], target: nodes[44]},
{ source: nodes[9], target: nodes[66]},
{ source: nodes[9], target: nodes[31]},
{ source: nodes[10], target: nodes[79]},
{ source: nodes[11], target: nodes[44]},
{ source: nodes[12], target: nodes[77]},
{ source: nodes[12], target: nodes[33]},
{ source: nodes[12], target: nodes[6]},
{ source: nodes[12], target: nodes[18]},
{ source: nodes[12], target: nodes[71]},
{ source: nodes[13], target: nodes[0]},
{ source: nodes[14], target: nodes[43]},
{ source: nodes[15], target: nodes[19]},
{ source: nodes[16], target: nodes[35]},
{ source: nodes[17], target: nodes[0]},
{ source: nodes[17], target: nodes[39]},
{ source: nodes[17], target: nodes[89]},
{ source: nodes[18], target: nodes[6]},
{ source: nodes[18], target: nodes[33]},
{ source: nodes[18], target: nodes[12]},
{ source: nodes[18], target: nodes[77]},
{ source: nodes[18], target: nodes[60]},
{ source: nodes[19], target: nodes[45]},
{ source: nodes[19], target: nodes[15]},
{ source: nodes[20], target: nodes[2]},
{ source: nodes[21], target: nodes[29]},
{ source: nodes[22], target: nodes[65]},
{ source: nodes[22], target: nodes[80]},
{ source: nodes[24], target: nodes[70]},
{ source: nodes[25], target: nodes[86]},
{ source: nodes[25], target: nodes[48]},
{ source: nodes[26], target: nodes[85]},
{ source: nodes[27], target: nodes[65]},
{ source: nodes[27], target: nodes[64]},
{ source: nodes[27], target: nodes[84]},
{ source: nodes[27], target: nodes[69]},
{ source: nodes[27], target: nodes[28]},
{ source: nodes[27], target: nodes[52]},
{ source: nodes[46], target: nodes[28]},
{ source: nodes[46], target: nodes[69]},
{ source: nodes[28], target: nodes[69]},
{ source: nodes[28], target: nodes[46]},
{ source: nodes[28], target: nodes[84]},
{ source: nodes[28], target: nodes[52]},
{ source: nodes[28], target: nodes[40]},
{ source: nodes[28], target: nodes[23]},
{ source: nodes[28], target: nodes[27]},
{ source: nodes[29], target: nodes[21]},
{ source: nodes[30], target: nodes[39]},
{ source: nodes[30], target: nodes[0]},
{ source: nodes[30], target: nodes[89]},
{ source: nodes[31], target: nodes[9]},
{ source: nodes[31], target: nodes[44]},
{ source: nodes[32], target: nodes[45]},
{ source: nodes[33], target: nodes[12]},
{ source: nodes[33], target: nodes[6]},
{ source: nodes[33], target: nodes[77]},
{ source: nodes[33], target: nodes[18]},
{ source: nodes[33], target: nodes[60]},
{ source: nodes[34], target: nodes[74]},
{ source: nodes[35], target: nodes[16]},
{ source: nodes[35], target: nodes[63]},
{ source: nodes[36], target: nodes[48]},
{ source: nodes[36], target: nodes[82]},
{ source: nodes[37], target: nodes[81]},
{ source: nodes[23], target: nodes[28]},
{ source: nodes[39], target: nodes[89]},
{ source: nodes[39], target: nodes[0]},
{ source: nodes[39], target: nodes[30]},
{ source: nodes[39], target: nodes[17]},
{ source: nodes[40], target: nodes[69]},
{ source: nodes[40], target: nodes[84]},
{ source: nodes[40], target: nodes[28]},
{ source: nodes[41], target: nodes[61]},
{ source: nodes[41], target: nodes[75]},
{ source: nodes[42], target: nodes[62]},
{ source: nodes[43], target: nodes[48]},
{ source: nodes[43], target: nodes[82]},
{ source: nodes[43], target: nodes[14]},
{ source: nodes[44], target: nodes[9]},
{ source: nodes[44], target: nodes[11]},
{ source: nodes[44], target: nodes[7]},
{ source: nodes[44], target: nodes[66]},
{ source: nodes[44], target: nodes[31]},
{ source: nodes[45], target: nodes[19]},
{ source: nodes[45], target: nodes[32]},
{ source: nodes[45], target: nodes[2]},
{ source: nodes[69], target: nodes[64]},
{ source: nodes[69], target: nodes[40]},
{ source: nodes[69], target: nodes[28]},
{ source: nodes[69], target: nodes[84]},
{ source: nodes[69], target: nodes[46]},
{ source: nodes[69], target: nodes[27]},
{ source: nodes[69], target: nodes[52]},
{ source: nodes[69], target: nodes[47]},
{ source: nodes[47], target: nodes[64]},
{ source: nodes[47], target: nodes[69]},
{ source: nodes[48], target: nodes[82]},
{ source: nodes[48], target: nodes[43]},
{ source: nodes[48], target: nodes[36]},
{ source: nodes[48], target: nodes[67]},
{ source: nodes[48], target: nodes[25]},
{ source: nodes[48], target: nodes[86]},
{ source: nodes[49], target: nodes[77]},
{ source: nodes[50], target: nodes[4]},
{ source: nodes[51], target: nodes[53]},
{ source: nodes[52], target: nodes[84]},
{ source: nodes[52], target: nodes[28]},
{ source: nodes[52], target: nodes[69]},
{ source: nodes[52], target: nodes[27]},
{ source: nodes[53], target: nodes[51]},
{ source: nodes[54], target: nodes[87]},
{ source: nodes[55], target: nodes[78]},
{ source: nodes[56], target: nodes[75]},
{ source: nodes[57], target: nodes[85]},
{ source: nodes[58], target: nodes[81]},
{ source: nodes[58], target: nodes[83]},
{ source: nodes[59], target: nodes[7]},
{ source: nodes[60], target: nodes[18]},
{ source: nodes[60], target: nodes[6]},
{ source: nodes[60], target: nodes[33]},
{ source: nodes[61], target: nodes[41]},
{ source: nodes[61], target: nodes[0]},
{ source: nodes[62], target: nodes[42]},
{ source: nodes[63], target: nodes[9]},
{ source: nodes[63], target: nodes[35]},
{ source: nodes[64], target: nodes[69]},
{ source: nodes[64], target: nodes[27]},
{ source: nodes[64], target: nodes[84]},
{ source: nodes[64], target: nodes[47]},
{ source: nodes[65], target: nodes[27]},
{ source: nodes[65], target: nodes[22]},
{ source: nodes[66], target: nodes[9]},
{ source: nodes[66], target: nodes[44]},
{ source: nodes[67], target: nodes[48]},
{ source: nodes[67], target: nodes[86]},
{ source: nodes[68], target: nodes[73]},
{ source: nodes[68], target: nodes[38]},
{ source: nodes[70], target: nodes[0]},
{ source: nodes[70], target: nodes[24]},
{ source: nodes[38], target: nodes[73]},
{ source: nodes[38], target: nodes[68]},
{ source: nodes[71], target: nodes[72]},
{ source: nodes[71], target: nodes[12]},
{ source: nodes[72], target: nodes[71]},
{ source: nodes[73], target: nodes[38]},
{ source: nodes[73], target: nodes[68]},
{ source: nodes[74], target: nodes[34]},
{ source: nodes[75], target: nodes[56]},
{ source: nodes[75], target: nodes[84]},
{ source: nodes[75], target: nodes[41]},
{ source: nodes[76], target: nodes[8]},
{ source: nodes[77], target: nodes[12]},
{ source: nodes[77], target: nodes[33]},
{ source: nodes[77], target: nodes[6]},
{ source: nodes[77], target: nodes[18]},
{ source: nodes[77], target: nodes[49]},
{ source: nodes[78], target: nodes[55]},
{ source: nodes[79], target: nodes[10]},
{ source: nodes[80], target: nodes[22]},
{ source: nodes[81], target: nodes[58]},
{ source: nodes[81], target: nodes[37]},
{ source: nodes[81], target: nodes[2]},
{ source: nodes[88], target: nodes[3]},
{ source: nodes[83], target: nodes[58]},
{ source: nodes[84], target: nodes[28]},
{ source: nodes[84], target: nodes[52]},
{ source: nodes[84], target: nodes[69]},
{ source: nodes[84], target: nodes[40]},
{ source: nodes[84], target: nodes[27]},
{ source: nodes[84], target: nodes[75]},
{ source: nodes[84], target: nodes[64]},
{ source: nodes[85], target: nodes[57]},
{ source: nodes[85], target: nodes[26]},
{ source: nodes[86], target: nodes[67]},
{ source: nodes[86], target: nodes[25]},
{ source: nodes[86], target: nodes[48]},
{ source: nodes[87], target: nodes[54]},
{ source: nodes[82], target: nodes[48]},
{ source: nodes[82], target: nodes[43]},
{ source: nodes[82], target: nodes[36]},
{ source: nodes[89], target: nodes[0]},
{ source: nodes[89], target: nodes[39]},
{ source: nodes[89], target: nodes[30]},
{ source: nodes[89], target: nodes[17]},
]
